version: '3.8'
services:
  php:
    build:
      context: ./php
    container_name: api_autos_php
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: api_autos_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  composer:
    image: composer:latest
    container_name: api_autos_composer
    volumes:
      - .:/app
    working_dir: /app
    command: install

  redis:
    image: redis:7
    container_name: api_autos_redis
    ports:
      - "6379:6379"
